### ISSUE TITLE
simplify the shutdown

### ISSUE THREAD

**Issue by patriknw** [akka/akka-http-quickstart-java.g8#15]
The reading from stdin doesn't always work (mvn). Was fixed in scala sample already https://github.com/akka/akka-http-quickstart-scala.g8/pull/35/files

**Comment by raboof** [comment]
Yes, let's do it when akka 2.5.10 is released with https://github.com/akka/akka/issues/24303

**Comment by patriknw** [comment]
but why is the Await needed in the first place? Isn't the jvm kept alive until all threads of the ActorSystem has been terminated anyway?

**Comment by raboof** [comment]
You're right that doesn't seem necessary either!

**Comment by patriknw** [comment]
unless sbt/mvn/gradle does something special when running a main in process. Trying it out in all 3 is needed.
