### ISSUE TITLE
NoSuchElementException when asking for a non existing user

### ISSUE THREAD

**Issue by pmihnea** [akka/akka-http-quickstart-java.g8#17]
GET http://localhost:8080/users/user-4

[ERROR] [03/06/2018 17:38:41.501] [helloAkkaHttpServer-akka.actor.default-dispatcher-8] [akka.actor.ActorSystemImpl(helloAkkaHttpServer)] Error during processing of request: 'No value present'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:151)
	at com.lightbend.akka.http.sample.UserRoutes.lambda$getUser$4(UserRoutes.java:75)

**Comment by raboof** [comment]
I agree it would be much nicer to produce a 404 in that case. Would you be interested in preparing a PR?

**Comment by patriknw** [comment]
I think I noticed the same but didn't follow up. 
Is there something wrong/missing with `rejectEmptyResponse`?

I switched from:
```java
          return rejectEmptyResponse(() ->
            onSuccess(
              () -> maybeUser,
              performed ->
                complete(StatusCodes.OK, (User) performed.get(), Jackson.<User>marshaller())
            )
          );
```

to:
```java
     return onSuccess(() -> maybeUser,
          result -> {
            if (result.isPresent())
              return complete(StatusCodes.OK, result.get(), Jackson.<User>marshaller());
            else
              return complete(StatusCodes.NOT_FOUND);
          }
      );
```

**Comment by mmchougule** [comment]
@raboof created a PR! :)

**Comment by raboof** [comment]
Thanks for the improvement!
