### ISSUE TITLE
sbt restart command not found in akka-http-quickstart-java

### ISSUE THREAD

**Issue by jmnght** [akka/akka-http-quickstart-java.g8#36]
I'm trying the akka-http quick start guide here: https://developer.lightbend.com/guides/akka-http-quickstart-java/
When executing `reStart` in `sbt`, I'm getting an error saying `Not a valid command`. Any idea why?

**Comment by raboof** [comment]
That is odd, this seems to work for me. How did you obtain your akka-http-quickstart-java project? Did you start sbt in the `akka-http-quickstart-java` folder?

**Comment by jrudolph** [comment]
Probably outdated by now.
