### ISSUE TITLE
Port the new quickstart :-)

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http-quickstart-java.g8#7]
The new quickstart is here in Scala: https://github.com/akka/akka-http-quickstart-scala.g8
We should port it to Java.

I remember there was community interest in helping us out  on that - that would be awesome!

**Comment by agolubev** [comment]
Started this. Currently in the middle.

**Comment by agolubev** [comment]
@ktoso,  PR is pushed. Waiting for a feedback

**Comment by ktoso** [comment]
Awesome, thanks a ton 👍

**Comment by ktoso** [comment]
Thanks @agolubev
